<?php
// from Brett and Daniel.
function icecream_poll_menu() {
    $items['icecream_poll'] = array(
        'title' => 'Ice Cream Poll',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('poll_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['poll_success'] = array(
        'title' => 'Success',
        'page callback' => 'poll_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function poll_form() {
    $flavors = array('Vanilla' => 'Vanilla', 'Chocolate' => 'Chocolate', 'Cherry' => 'Cherry', 'Pannacota' => 'Pannacota', 'Rainbow Sherbet' => 'Rainbow Sherbet');

    $form['flavor'] = array(
        '#title' => 'Ice Cream Poll',
        '#type' => 'radios',
        '#default_value' => 0,
        '#options' => $flavors,
        '#description' => t("Select your favorite icecream"),
    );
    $form['state'] = array(
        '#title' => 'State',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_state'),
        '#description' => t("Enter your Home-State"),
    );
    $form['submit'] = array(
        '#value' => 'Go',
        '#type' => 'submit',
    );
    return $form;
}

function element_validate_state($element) {
    $state = $element['#value'];
    $valid_states = array(
        'AL', 'ALABAMA',
        'AK', 'ALASKA',
        'AS', 'AMERICAN SAMOA',
        'AZ', 'ARIZONA',
        'AR', 'ARKANSAS',
        'CA', 'CALIFORNIA',
        'CO', 'COLORADO',
        'CT', 'CONNECTICUT',
        'DE', 'DELAWARE',
        'DC', 'DISTRICT OF COLUMBIA',
        'FM', 'FEDERATED STATES OF MICRONESIA',
        'FL', 'FLORIDA',
        'GA', 'GEORGIA',
        'GU', 'GUAM GU',
        'HI', 'HAWAII',
        'ID', 'IDAHO',
        'IL', 'ILLINOIS',
        'IN', 'INDIANA',
        'IA', 'IOWA',
        'KS', 'KANSAS',
        'KY', 'KENTUCKY',
        'LA', 'LOUISIANA',
        'ME', 'MAINE',
        'MH', 'MARSHALL ISLANDS',
        'MD', 'MARYLAND',
        'MA', 'MASSACHUSETTS',
        'MI', 'MICHIGAN',
        'MN', 'MINNESOTA',
        'MS', 'MISSISSIPPI',
        'MO', 'MISSOURI',
        'MT', 'MONTANA',
        'NE', 'NEBRASKA',
        'NV', 'NEVADA',
        'NH', 'NEW HAMPSHIRE',
        'NJ', 'NEW JERSEY',
        'NM', 'NEW MEXICO',
        'NY', 'NEW YORK',
        'NC', 'NORTH CAROLINA',
        'ND', 'NORTH DAKOTA',
        'MP', 'NORTHERN MARIANA ISLANDS',
        'OH', 'OHIO',
        'OK', 'OKLAHOMA',
        'OR', 'OREGON',
        'PW', 'PALAU',
        'PA', 'PENNSYLVANIA',
        'PR', 'PUERTO RICO',
        'RI', 'RHODE ISLAND',
        'SC', 'SOUTH CAROLINA',
        'SD', 'SOUTH DAKOTA',
        'TN', 'TENNESSEE',
        'TX', 'TEXAS',
        'UT', 'UTAH',
        'VT', 'VERMONT',
        'VI', 'VIRGIN ISLANDS',
        'VA', 'VIRGINIA',
        'WA', 'WASHINGTON',
        'WV', 'WEST VIRGINIA',
        'WI', 'WISCONSIN',
        'WY', 'WYOMING',
    );

    // uppercase
    $state = strtoupper($state);
    // test
    if (!in_array($state, $valid_states)) {
        form_error($element, t(" $state is not a valid state."));
    }

}

function poll_form_submit($form, &$form_state) {
    $_SESSION['flavor'] = $form_state['values']['flavor'];
    $_SESSION['state'] = strtoupper($form_state['values']['state']);
    $form_state['redirect'] = 'poll_success';
}

function poll_success() {
    return '<p>Thank You! We have you down for ' . $_SESSION['flavor'] . ' in ' . $_SESSION['state'] . '.</p>';
}
