<?php
function greeting_with_hooks_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello_hooks',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell_hooks',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}
function say_hello_hooks() {
    return '<p>Hello my dear friend!</p>';
}
function say_farewell_hooks() {
    return '<p>Fare thee well my dear friend!</p>';
}
function greeting_with_hooks_user_login(&$edit, $account){
    // echo '<pre>';
    // var_dump($account);
    // echo '</pre>';
    // exit;

    // echo '<pre>';
    // var_dump($edit);
    // echo '</pre>';
    // exit;

    $_GET['destination'] = 'hello_friend';
}
function greeting_with_hooks_user_logout(){
    $_GET['destination'] = 'farewell';
}