<?php

    function validate_ping_pong_menu() {
        $items = array();
        $items['validate_ping_pong'] = array(
            'title' => 'Ping Pong Problem with Validation',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('validate_ping_pong_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['validate_ping_pong_success_page'] = array(
            'title' => 'Success',
            'page callback' => 'validate_ping_pong_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function validate_ping_pong_form() {
        $form['count_goal'] = array(
            '#title' => 'Count Goal',
            '#type' => 'textfield',
            '#description' => t('Please enter the number you want to count up to.'),
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Go',
        );

        return $form;
    }

    function validate_ping_pong_form_submit($form, &$form_state) {

    $count_max = $form_state['values']['count_goal'];
    $pingpong_output = array();

    for ($i=1; $i <= $count_max; $i++) {
        if ($i % 3 == 0 && $i % 5 == 0) {
            array_push($pingpong_output, "ping-pong");
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "ping");
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "pong");
        } else {
            array_push($pingpong_output, $i);
        }
    }

        $_SESSION['validate_ping_pong_output'] = $pingpong_output;
        $form_state['redirect'] = 'validate_ping_pong_success_page';
    }

    function validate_ping_pong_success() {
        $output = '<ul>';
        foreach ($_SESSION['validate_ping_pong_output'] as $value) {
            $output = $output . '<li>' . $value . '</li>';
        }
        $output = $output . '</ul>';
        return "Hooray! $output";
    }
