<?php

function hello_user_menu() {
  $items['new_user_created'] = array(
      'title' => "New User Created!",
      'page callback' => 'new_user_created',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
  return $items;
}

function new_user_created() {
  return '<p>You created a new account.</p>';
}

function hello_user_user_insert(&$edit, $account, $category) {
  $_GET['destination'] = 'new_user_created';
}
