<?php
function greeting_menu() {
    $items = array();
    // incidentally, line 3 is not needed. It's there for clarity to show that $items is just a normal blank array that we are adding key-value pairs to, and then returning.
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function say_hello() {
    return '<p>Hello my dear friend!</p>';
}

function say_farewell() {
    return '<p>Fare thee well my dear friend!</p>';
}